// ═══════════════════════════════════════
//  LANGUAGE SYSTEM — EN + MY (Burmese)
// ═══════════════════════════════════════
const LANG={
en:{
nav:{title:"Digital Science Museum",physics:"Physics",math:"Mathematics",chemistry:"Chemistry",space:"Space"},
home:{title:'Digital Science <em>Museum</em>',sub:"Explore. Interact. Discover the wonders of science.",
  physics_d:"Atoms, forces, electricity, light, energy — the laws that govern our universe",
  math_d:"Primes, fractals, geometry, probability — the hidden language of reality",
  chemistry_d:"Elements, bonds, reactions, acids — the science of matter and change",
  space_d:"Planets, rockets, stars, telescopes — journey through the cosmos",ex:"exhibits",
  feat_riemann_badge:'⭐ FEATURED',feat_riemann_title:'Riemann Zeta Function',feat_riemann_sub:'The deepest unsolved mystery in mathematics',feat_riemann_desc:'Explore how the zeros of ζ(s) secretly encode the distribution of prime numbers — the $1M Millennium Prize problem.',
  feat_ai_badge:'🤖 INTERACTIVE',feat_ai_title:'How AI & LLMs Work',feat_ai_sub:'Inside the brain of ChatGPT & Claude',feat_ai_desc:'Neural networks, tokenization, attention mechanisms — see how billions of parameters learn to understand language.',
  feat_pi_badge:'🥧 PI DAY',feat_pi_title:'Pi Day Special',feat_pi_sub:'March 14 = 3.14 = π',feat_pi_desc:'5 interactive ways to discover, estimate, and visualize the most famous number in all of mathematics.',
  feat_rocket_badge:'🚀 SIMULATION',feat_rocket_title:'Rocket Launch Simulator',feat_rocket_sub:'Can you reach orbit?',feat_rocket_desc:'Configure thrust, fuel, payload and launch angle. Real rocket physics — every parameter changes your trajectory.',
  feat_city_badge:'🏙️ NEW',feat_city_title:'Yangon City Energy Sim',feat_city_sub:'Power a city. Save the planet.',feat_city_desc:'Design the perfect energy mix for Yangon. Balance renewables vs fossil fuels — see pollution, heat islands, and grid reliability change in real time.',
  feat_explore:'Explore →',feat_header:'✦ Featured Exhibits',feat_sub:'Handpicked for depth, beauty, and interactivity',feat_explore_subject:'Explore by Subject'},
back:"← Back to",
sec:{
  physics:{t:"Physics",d:"Explore the fundamental forces and building blocks of our universe"},
  math:{t:"Mathematics",d:"Discover patterns, proofs, and the hidden structures of numbers"},
  chemistry:{t:"Chemistry",d:"From atoms to reactions — the science of matter and change"},
  space:{t:"Space",d:"Journey through the solar system, stars, and the cosmos"}
},
// PHYSICS
p_atom:{t:"Atom Explorer",d:"Build atoms by adding protons, neutrons, and electrons. Create different elements and see how atomic structure determines chemistry.",tag:"Interactive Model",
  protons:"Protons",neutrons:"Neutrons",electrons:"Electrons",element:"Element",mass:"Mass Number",charge:"Charge",neutral:"Neutral",ion:"Ion",shell:"Shell",
  exp_t:"How Atoms Work",exp:"Every atom has a <strong>nucleus</strong> made of protons (+) and neutrons (0), surrounded by orbiting electrons (−). The number of protons defines the element: 1 proton = Hydrogen, 6 = Carbon, 26 = Iron. When electrons ≠ protons, the atom becomes an <strong>ion</strong> with a net electric charge."},
p_forces:{t:"Forces & Newton's Laws",d:"Apply forces to objects and watch Newton's three laws in action. See how mass, acceleration, and friction interact.",tag:"Simulation",
  mass:"Mass",force:"Applied Force",friction:"Friction",velocity:"Velocity",accel:"Acceleration",reset:"Reset",
  exp_t:"Newton's Laws of Motion",exp:"<strong>1st Law:</strong> Objects stay at rest or in motion unless a force acts. <strong>2nd Law:</strong> F = ma — force equals mass times acceleration. <strong>3rd Law:</strong> Every action has an equal and opposite reaction. Watch how increasing mass reduces acceleration for the same force!"},
p_circuits:{t:"Electricity & Circuits",d:"Build simple circuits with batteries, resistors, and bulbs. See how voltage, current, and resistance relate through Ohm's Law.",tag:"Interactive",
  voltage:"Voltage (V)",resistance:"Resistance (Ω)",current:"Current (A)",power:"Power (W)",
  exp_t:"Ohm's Law: V = IR",exp:"Electric current flows like water through pipes. <strong>Voltage</strong> is the pressure pushing electrons. <strong>Resistance</strong> opposes flow. <strong>Current</strong> = Voltage ÷ Resistance. More voltage → more current. More resistance → less current. Power (watts) = V × I."},
p_light:{t:"Light, Lenses & Telescopes",d:"See how light bends through lenses, how telescopes magnify distant objects, and how convergence brings images into focus.",tag:"Optics Sim",
  focal:"Focal Length",obj_dist:"Object Distance",convex:"Convex Lens",concave:"Concave Lens",
  exp_t:"How Lenses & Telescopes Work",exp:"A <strong>convex lens</strong> converges light rays to a focal point — this is how magnifying glasses and telescope objectives work. A <strong>telescope</strong> uses two lenses: the objective gathers light from distant objects, and the eyepiece magnifies the image. The ratio of focal lengths determines magnification."},
p_energy:{t:"Energy & Waves",d:"Explore kinetic and potential energy with a pendulum, and create transverse and longitudinal waves.",tag:"Simulation",
  ke:"Kinetic Energy",pe:"Potential Energy",total:"Total Energy",amp:"Amplitude",freq:"Frequency",
  exp_t:"Conservation of Energy",exp:"Energy cannot be created or destroyed — only transformed. A swinging pendulum converts <strong>potential energy</strong> (height) to <strong>kinetic energy</strong> (motion) and back. At the top: max PE, min KE. At the bottom: max KE, min PE. Total energy stays constant (ignoring friction)."},
// MATH
m_primes:{t:"Prime Number Sieve",d:"Watch the ancient Sieve of Eratosthenes find primes. Step through the algorithm or race to find them all!",tag:"Interactive Game",
  start:"Start",reset:"Reset",step:"Step",found:"Primes found",checking:"Checking",
  exp_t:"The Sieve of Eratosthenes",exp:"A prime number is divisible only by 1 and itself. The sieve works by starting at 2 and crossing out all its multiples, then moving to the next uncrossed number. After processing up to √N, all remaining numbers are prime. This 2,300-year-old algorithm is still used in modern computing!"},
m_fractals:{t:"Fractal Explorer",d:"Watch a tree branch infinitely, then dive into the Mandelbrot set. Simple rules create infinite complexity — the magic of fractals.",tag:"Exploration",
  tree:"Fractal Tree",mandel:"Mandelbrot Set",depth:"Depth",angle:"Angle",ratio:"Shrink Ratio",wind:"Wind",branches:"Branches",
  zoom:"Zoom",detail:"Detail",reset:"Reset View",coords:"Coordinates",
  exp_t:"What Are Fractals?",exp:"Fractals are shapes with <strong>self-similarity</strong> — they look similar at every scale. A fractal tree demonstrates this beautifully: each branch splits into smaller copies of itself. Increase the depth and watch complexity explode — 1 branch becomes 2, then 4, 8, 16, 32... at depth 13 there are over 8,000 branches! The Mandelbrot set shows the same idea algebraically: iterating z = z² + c reveals infinite detail at every zoom level. Fractals appear everywhere in nature: trees, ferns, coastlines, snowflakes, blood vessels, and even galaxy clusters."},
m_pythag:{t:"Pythagorean Theorem",d:"Drag the triangle's vertices and watch the visual proof: the square on the hypotenuse equals the sum of squares on the other sides.",tag:"Visual Proof",
  side_a:"Side a",side_b:"Side b",hyp:"Hypotenuse c",
  exp_t:"a² + b² = c²",exp:"In any right triangle, the square of the hypotenuse (longest side) equals the sum of squares of the other two sides. This isn't just abstract — it's how GPS calculates distances, how builders ensure walls are straight, and how video games compute diagonal movement!"},
m_prob:{t:"Probability & Statistics",d:"Roll dice, flip coins, and watch probability distributions emerge from randomness.",tag:"Interactive",
  roll:"Roll!",rolls:"Rolls",expected:"Expected",actual:"Actual",coins:"Coins",dice:"Dice",
  exp_t:"The Law of Large Numbers",exp:"Individual random events are unpredictable, but patterns emerge over many trials. Roll one die — any face is equally likely (1/6). Roll 1000 times — each face appears roughly 167 times. This is the <strong>Law of Large Numbers</strong>, the foundation of statistics, insurance, and scientific experiments."},
m_trig:{t:"Trigonometry & Unit Circle",d:"Explore sine, cosine, and tangent on the unit circle. See how circular motion creates wave patterns.",tag:"Interactive",
  angle:"Angle",sin:"sin",cos:"cos",tan:"tan",
  exp_t:"The Unit Circle",exp:"Place a point on a circle of radius 1. The x-coordinate is <strong>cosine</strong>, the y-coordinate is <strong>sine</strong>. As the point moves around the circle, these values trace out smooth waves. This connects circular motion to oscillation — explaining everything from sound waves to planetary orbits to AC electricity."},
// CHEMISTRY
c_ptable:{t:"Periodic Table",d:"Explore all 118 elements. Click any element to discover its properties, category, and real-world uses.",tag:"Reference",
  anum:"Atomic Number",sym:"Symbol",name:"Name",amass:"Atomic Mass",cat:"Category",
  exp_t:"The Periodic Table",exp:"Dmitri Mendeleev arranged elements by atomic number and discovered a pattern: elements in the same <strong>column (group)</strong> have similar properties. Alkali metals (left) are reactive. Noble gases (right) are stable. This table predicts how elements behave, bond, and react — it's chemistry's most powerful tool."},
c_states:{t:"States of Matter",d:"Control temperature and watch particles transform between solid, liquid, and gas. See molecular behavior change in real time.",tag:"Particle Sim",
  temp:"Temperature",solid:"Solid",liquid:"Liquid",gas:"Gas",
  exp_t:"Kinetic Molecular Theory",exp:"Matter is made of particles in constant motion. In <strong>solids</strong>, particles vibrate in fixed positions (strong bonds). In <strong>liquids</strong>, particles slide past each other (weaker bonds). In <strong>gases</strong>, particles fly freely (minimal bonds). Temperature = average kinetic energy of particles. Add heat → particles move faster → state changes."},
c_bonds:{t:"Chemical Bonding",d:"See how atoms share or transfer electrons to form ionic and covalent bonds. Build simple molecules.",tag:"Interactive",
  ionic:"Ionic Bond",covalent:"Covalent Bond",transfer:"Electron Transfer",share:"Electron Sharing",
  exp_t:"Why Atoms Bond",exp:"Atoms bond to achieve stable electron configurations (usually 8 outer electrons — the 'octet rule'). In <strong>ionic bonds</strong>, one atom gives electrons to another (like NaCl — table salt). In <strong>covalent bonds</strong>, atoms share electrons (like H₂O — water). Bond type determines a substance's properties: melting point, conductivity, solubility."},
c_ph:{t:"pH & Acids/Bases",d:"Explore the pH scale from 0-14. See how acids and bases differ and what happens when they mix.",tag:"Interactive",
  acidic:"Acidic",neutral:"Neutral",basic:"Basic",ph:"pH Level",
  exp_t:"The pH Scale",exp:"pH measures hydrogen ion concentration on a scale of 0-14. <strong>Acids</strong> (pH < 7) have excess H⁺ ions — vinegar, lemon juice, stomach acid. <strong>Bases</strong> (pH > 7) have excess OH⁻ ions — soap, bleach, baking soda. <strong>Neutral</strong> (pH = 7) — pure water. Each pH unit is a 10× difference in concentration!"},
c_react:{t:"Balancing Equations",d:"Balance chemical equations by adjusting coefficients. Conservation of mass means atoms in = atoms out.",tag:"Puzzle Game",
  balanced:"Balanced!",notyet:"Not balanced yet",check:"Check",next:"Next",
  exp_t:"Conservation of Mass",exp:"In any chemical reaction, atoms are rearranged but never created or destroyed. That's why equations must <strong>balance</strong>: same number of each atom on both sides. This principle (Lavoisier, 1789) is fundamental to all chemistry. Balancing equations is like solving a puzzle where matter is conserved."},
// SPACE
s_solar:{t:"Solar System Explorer",d:"Navigate all 8 planets. Click for facts about distance, size, moons, and orbital periods.",tag:"Exploration",
  speed:"Time Speed",dist:"Distance from Sun",diam:"Diameter",moons:"Moons",day:"Day Length",year:"Year Length",
  exp_t:"Our Solar System",exp:"Eight planets orbit our Sun, held by gravity. The inner rocky planets (Mercury-Mars) are small and dense. The outer gas giants (Jupiter-Neptune) are massive. Earth sits in the <strong>habitable zone</strong> — just the right distance for liquid water. The solar system formed 4.6 billion years ago from a collapsing cloud of gas and dust."},
s_rocket:{t:"Rocket Launch Simulator",d:"Configure engine, thrust, fuel, payload and staging. Sliders auto-adjust — find the optimal build to reach the Moon!",tag:"Physics Game",
  thrust:"Thrust",angle:"Launch Angle",fuel:"Fuel",payload:"Payload",alt:"Altitude (km)",vel:"Velocity (m/s)",launch:"Launch!",reset:"Reset",orbit:"Target Orbit",
  engine:"Engine",stages:"Stages",mass:"Mass",twr:"TWR",dv:"Δv Budget",predict:"Prediction",mission:"Mission Control",optimize:"Optimize to reach the Moon 🌕",
  kerosene:"Kerosene/LOX",hydrogen:"Hydrogen/LOX",methane:"Methane/LOX",
  eng_hint:"ISP",stg_hint:"drop dead weight",thr_hint:"↑TWR",fuel_hint:"↑Δv ↑mass",pay_hint:"↑mass ↓Δv",ang_hint:"pitch angle",
  auto_adj:"Auto-adjusted",
  exp_t:"Rocket Science",exp:"Rockets work by Newton's 3rd Law: exhaust gases push down, the rocket pushes up. The <strong>thrust-to-weight ratio</strong> must exceed 1 to lift off. More fuel = more burn time but more weight. More payload = harder to reach orbit. Launch angle matters: too steep wastes fuel fighting gravity, too shallow can't gain altitude. Real rockets use multiple stages, dropping empty tanks to reduce mass. Choose your engine wisely: hydrogen gives more efficiency (ISP) but needs bigger tanks."},
s_moon:{t:"Moon Phases",d:"See why the Moon changes shape. Drag the Moon around Earth and watch phases change from new to full and back.",tag:"Interactive Model",
  phase:"Current Phase",new:"New Moon",waxc:"Waxing Crescent",firstq:"First Quarter",waxg:"Waxing Gibbous",full:"Full Moon",wang:"Waning Gibbous",lastq:"Last Quarter",wanc:"Waning Crescent",
  exp_t:"Why the Moon Has Phases",exp:"The Moon doesn't produce light — it reflects sunlight. As the Moon orbits Earth (~29.5 days), we see different amounts of its lit side. <strong>New Moon</strong>: Moon between Earth and Sun (dark). <strong>Full Moon</strong>: Earth between Moon and Sun (fully lit). The phases cycle predictably, which is why ancient civilizations used lunar calendars."},
s_star:{t:"Star Life Cycle",d:"Follow a star from birth in a nebula through main sequence, red giant, and its dramatic end — supernova or white dwarf.",tag:"Visual Journey",
  nebula:"Nebula",protostar:"Protostar",mainseq:"Main Sequence",redgiant:"Red Giant",supernova:"Supernova",neutron:"Neutron Star",blackhole:"Black Hole",whitedwarf:"White Dwarf",
  exp_t:"The Life of Stars",exp:"Stars are born in <strong>nebulae</strong> (gas clouds) that collapse under gravity. Nuclear fusion ignites, and a star enters the <strong>main sequence</strong> (like our Sun). After billions of years, fuel runs low. Small stars become red giants → white dwarfs. Massive stars → supergiants → <strong>supernovae</strong> → neutron stars or black holes. Every heavy element in your body was forged inside a star."},
s_tele:{t:"How Telescopes Work",d:"See how refracting and reflecting telescopes gather and focus light to reveal distant objects in space.",tag:"Optics Sim",
  refract:"Refracting",reflect:"Reflecting",aperture:"Aperture",mag:"Magnification",
  exp_t:"Telescopes: Seeing the Invisible",exp:"Telescopes collect more light than our eyes can, revealing faint distant objects. <strong>Refracting telescopes</strong> use lenses to bend (refract) light to a focal point. <strong>Reflecting telescopes</strong> use curved mirrors — they can be much larger and have no chromatic aberration. The Hubble Space Telescope's 2.4m mirror has shown us galaxies 13 billion light-years away."},
// PI DAY SPECIAL
pi:{t:"Pi Day Special: The Magic of π",d:"Celebrate Pi Day (3/14) with five interactive ways to discover, visualize, and estimate the most famous number in mathematics.",tag:"Special Event",
  banner:"Happy Pi Day! March 14 = 3.14 = π",
  tab_monte:"Monte Carlo",tab_buffon:"Buffon's Needle",tab_digits:"Pi Digits",tab_leibniz:"Leibniz Series",tab_circle:"C ÷ d = π",
  monte_title:"Estimate π by Throwing Random Darts",
  monte_info:"Drop random points in a square with an inscribed circle. The ratio of points inside the circle to total points approximates π/4. More points = better estimate!",
  inside_circle:"Inside Circle",total_points:"Total Points",error:"Error",
  start_rain:"Start Rain",stop_rain:"Stop",
  buffon_title:"Buffon's Needle Problem (1777)",
  buffon_info:"Drop needles of length L onto parallel lines spaced d apart. The probability of crossing a line is 2L/(πd). Count crossings to estimate π!",
  needles_dropped:"Needles",crossing:"Crossing Lines",drop_needles:"Drop Needles",
  digits_title:"The First 1000 Digits of Pi",
  digits_info:"Each digit 0-9 is color-coded. Pi's digits appear random — no pattern has ever been found. Are all digits equally common?",
  showing:"Showing",digits_of_pi:"digits of π",
  freq_title:"Digit Frequency Distribution",
  freq_info:"In a truly random sequence, each digit would appear exactly 10% of the time. Pi's digits are remarkably close!",
  leibniz_title:"Leibniz Series: Infinite Sum → π",
  leibniz_info:"The Leibniz formula: π/4 = 1 - 1/3 + 1/5 - 1/7 + ... Watch this infinite series slowly converge to π. It's beautiful but painfully slow!",
  terms:"Terms",current_sum:"Current Estimate",animate:"Animate",
  circle_title:"Why C ÷ d = π (Always!)",
  circle_info:"Roll a circle along a line. The distance it travels in one revolution equals exactly π times its diameter. This is the original definition of π!",
  radius:"Radius",roll_circle:"Roll Circle",revolutions:"Revolutions",distance:"Distance",
  exp_t:"The Magic of Pi (π)",exp:"<strong>Pi (π ≈ 3.14159...)</strong> is the ratio of a circle's circumference to its diameter — and it appears everywhere in mathematics and nature. It's <strong>irrational</strong> (never-ending, non-repeating decimals) and <strong>transcendental</strong> (can't be a root of any polynomial). Pi appears in probability (Buffon's needle), infinite series (Leibniz, Euler), quantum physics, general relativity, Fourier transforms, and even the distribution of prime numbers. March 14 (3/14) is celebrated worldwide as Pi Day — also Einstein's birthday!"},
// RIEMANN ZETA
riemann:{t:"Riemann Zeta Function",d:"Explore the deepest unsolved problem in mathematics — how the zeros of the Zeta function secretly encode the pattern of prime numbers.",tag:"Advanced Interactive",
  tab1:"Critical Line",tab2:"Prime Staircase",tab3:"The Grand Connection",
  cl_title:"Non-Trivial Zeros on the Critical Line",
  cl_info:"All 30 known zeros shown lie on Re(s) = ½. The Riemann Hypothesis conjectures ALL non-trivial zeros lie here. Hover to inspect.",
  strip:"Critical Strip",cline:"Critical Line Re=½",zeros_lbl:"Non-trivial Zeros",
  showing_n:"Showing first {n} non-trivial zeros",
  ps_title:"Prime Counting Function π(x) vs Li(x)",
  ps_info:"The staircase π(x) counts primes up to x. The smooth curve Li(x) is a remarkably good approximation — their difference encodes deep structure.",
  x_range:"x range",prime_count:"prime counting",li_approx:"log integral approx",error_lbl:"Difference",
  gc_title:"How Zeros Sculpt the Primes",
  gc_info:"Add zeros one by one and watch the smooth Li(x) curve develop oscillations that match the prime staircase. Each zero adds a correction — this is the profound connection Riemann discovered.",
  num_zeros:"Zeros used",zeros_used:"{n} zeros from the critical line",zeros_word:"zeros",
  actual:"actual primes",smooth:"smooth (no zeros)",recon:"Reconstruction",
  hint0:"Li(x) alone is smooth — it misses the staircase steps entirely",
  hint_few:"A few zeros begin to create oscillations toward the prime staircase...",
  hint_mid:"The reconstruction increasingly matches the jumps at prime numbers!",
  hint_many:"With many zeros, the reconstruction closely follows π(x) — zeros encode primes!",
  axis_x:"x",
  exp_t:"The Riemann Hypothesis",exp:"The <strong>Riemann Zeta function ζ(s)</strong> connects the world of complex analysis to prime numbers. Riemann discovered that the <strong>non-trivial zeros</strong> of ζ(s) encode precise information about how primes are distributed. His hypothesis — that ALL non-trivial zeros have real part exactly ½ — remains unproven after 160+ years and carries a $1 million Millennium Prize. If true, it would confirm that primes are distributed as regularly as possible, with no unexpected conspiracies in their pattern."},
// CITY ENERGY
city:{t:"Yangon City Energy Simulator",d:"Design the optimal energy mix for Yangon. Balance coal, gas, solar, wind, and hydro power — see how your choices affect carbon emissions, air quality, heat islands, and grid reliability in real time.",tag:"Simulation Game",
  energy_mix:"Energy Mix",green_space:"Green Space",hour:"Time of Day",day_cycle:"Day Cycle",pause:"Pause",
  metrics:"City Metrics",emissions:"Emissions",air_quality:"Air Quality Index",reliability:"Grid Reliability",
  heat_island:"Heat Island",renew_pct:"Renewable %",cost:"Avg Cost",daily_reliability:"24-Hour Reliability Profile",
  verdict_excellent:"Exemplary Green City! Clean air, reliable grid, cool streets.",
  verdict_good:"Good progress! City is moving toward sustainability.",
  verdict_moderate:"Moderate — room for improvement in emissions or reliability.",
  verdict_poor:"Critical pollution levels! Heavy fossil fuel dependence is harming the city.",
  advice_reliability:"⚡ Grid reliability is dangerously low. Renewables need backup — add gas or hydro for dispatchable power, or the city faces blackouts at night.",
  advice_carbon:"🏭 CO₂ emissions are very high. Reduce coal dependency and increase solar/wind to cut carbon footprint. Even replacing coal with gas cuts emissions 40%.",
  advice_heat:"🌡️ Urban heat island is severe. Increase green spaces and reduce fossil fuel burning. Trees and parks provide natural cooling through evapotranspiration.",
  advice_perfect:"🌍 Outstanding! Your city has clean air, reliable power, and cool streets. This is what sustainable urban energy looks like.",
  advice_balance:"💡 Try balancing renewables with dispatchable sources. Solar peaks at noon but drops to zero at night — pair it with hydro or gas for 24/7 reliability.",
  exp_t:"Urban Energy & Climate Science",exp:"Cities consume over 75% of global energy and produce 70% of CO₂ emissions. The <strong>energy mix</strong> — the combination of sources powering a city — determines its carbon footprint, air quality, and urban heat. <strong>Coal</strong> produces 820g CO₂/kWh, while <strong>solar</strong> produces just 41g. But renewables face <strong>intermittency</strong>: solar works only during daylight, wind varies hourly. A smart grid balances clean sources with dispatchable backup. <strong>Urban heat islands</strong> occur when concrete and waste heat raise city temperatures 2-8°C above surrounding areas. Green spaces, trees, and clean energy all help cool cities."},
// AI & LLMs
ai:{t:"How AI & Large Language Models Work",d:"Peek inside the brain of an AI. Explore neural networks, tokenization, attention mechanisms, and how models like ChatGPT and Claude actually think.",tag:"Technology",
  tab_nn:"Neural Network",tab_tokens:"Tokens",tab_attention:"Attention",tab_scale:"Scale & Training",
  nn_title:"A Neural Network in Action",
  nn_info:"Neural networks are layers of connected 'neurons.' Each connection has a weight. Signals flow from input to output, transforming data at each layer. Click nodes to see activation propagate!",
  nn_fire:"Fire All Inputs",nn_random:"Randomize Weights",nn_hint:"Warm colors = high activation | Cool colors = low activation",
  tokens_title:"How AI Reads Text: Tokenization",
  tokens_info:"LLMs don't read letters — they break text into 'tokens' (words or word pieces). Each token becomes a number. Type something to see how it gets tokenized!",
  tokenize_btn:"Tokenize",
  attention_title:"The Attention Mechanism",
  attention_info:"Attention lets AI understand context by learning which words relate to which. 'It' in 'The cat sat because it was tired' attends to 'cat' — click any word to see what it focuses on.",
  scale_title:"The Scale of Modern AI",
  scale_info:"Modern LLMs have billions of parameters. Temperature controls creativity: low = predictable, high = surprising. See how parameter count and temperature affect AI behavior.",
  type_here:"Type text here...",token_count:"Token count",click_word:"Click a word to see its attention",
  params:"Parameters",temp:"Temperature",low:"Focused",high:"Creative",
  exp_t:"How LLMs Actually Work",exp:"Large Language Models like <strong>ChatGPT</strong> and <strong>Claude</strong> are trained on vast amounts of text to predict the next word. They use <strong>transformer architecture</strong> with self-attention — allowing each word to 'look at' every other word to understand context. Training involves adjusting billions of parameters (weights) to minimize prediction errors. The result is a model that captures patterns of language, reasoning, and knowledge. LLMs don't 'understand' like humans — they're incredibly sophisticated pattern-matching machines that can generate coherent, helpful text."}
},

my:{
  nav:{
    title:'ဒီဂျစ်တယ် သိပ္ပံပြတိုက်',
    physics:'ရူပဗေဒ',
    math:'သင်္ချာ',
    chemistry:'ဓာတုဗေဒ',
    space:'အာကာသ'
  },
  home:{
    title:'ဒီဂျစ်တယ် သိပ္ပံပြတိုက်',
    sub:'လေ့လာပါ။ လက်တွေ့စမ်းသပ်ပါ။ သိပ္ပံပညာရဲ့ အံ့ဖွယ်ရာတွေကို ရှာဖွေဖော်ထုတ်လိုက်ပါ။',
    physics_d:'အက်တမ်များ၊ အားများ၊ လျှပ်စစ်၊ အလင်းနှင့် စွမ်းအင် — စကြဝဠာကို ထိန်းကျောင်းမောင်းနှင်နေသော နိယာမများ',
    math_d:'ပရိုင်းကိန်းများ၊ ဖရက်တယ်လ်များ၊ ဂျီသြမေတြီနှင့် ဖြစ်တန်စွမ်း — လက်တွေ့ကမ္ဘာရဲ့ ဝှက်ဖုံးထားသော ဘာသာစကား',
    chemistry_d:'ဒြပ်စင်များ၊ ပေါင်းစည်းမှုများ၊ ဓာတ်ပြုမှုများနှင့် အက်ဆစ်များ — ဒြပ်ဝတ္ထုများနှင့် ပြောင်းလဲမှုဆိုင်ရာ သိပ္ပံပညာ',
    space_d:'ဂြိုဟ်များ၊ ဒုံးပျံများ၊ ကြယ်များနှင့် တယ်လီစကုပ်များ — စကြဝဠာအတွင်းသို့ ခရီးစဉ်',
    ex:'ပြကွက်များ',
    feat_riemann_badge:'⭐ အထူးပြကွက်',feat_riemann_title:'Riemann Zeta Function',feat_riemann_sub:'သင်္ချာလောကရဲ့ အနက်ရှိုင်းဆုံး အဖြေမထွက်သေးသော ပဟေဠိ',feat_riemann_desc:'Zeta(s) ရဲ့ သုည (zeros) များက ပရိုင်းကိန်းတွေရဲ့ တည်ရှိမှုကို ဘယ်လိုလျှို့ဝှက်စွာ ဖော်ပြနေသလဲဆိုတာ လေ့လာလိုက်ပါ။ ဒါဟာ ဒေါ်လာ ၁ သန်းဆုကြေးပေးထားတဲ့ Millennium Prize ပြဿနာပဲ ဖြစ်ပါတယ်။',
    feat_ai_badge:'🤖 လက်တွေ့စမ်းသပ်မှု',feat_ai_title:'AI နှင့် LLM များ မည်သို့အလုပ်လုပ်သနည်း',feat_ai_sub:'ChatGPT နှင့် Claude တို့ရဲ့ ဦးနှောက်အတွင်းပိုင်း',feat_ai_desc:'Neural networks၊ tokenization နှင့် attention mechanisms များ — ဘီလီယံနှင့်ချီသော parameters များက ဘာသာစကားကို နားလည်အောင် ဘယ်လိုသင်ယူသလဲဆိုတာ ကြည့်ရှုလိုက်ပါ။',
    feat_pi_badge:'🥧 ပိုင် (PI) နေ့',feat_pi_title:'ပိုင် (Pi) နေ့ အထူးအစီအစဉ်',feat_pi_sub:'မတ်လ ၁၄ ရက် = ၃.၁၄ = pi',feat_pi_desc:'သင်္ချာလောကမှာ အကျော်ကြားဆုံး ကိန်းဂဏန်းကို ရှာဖွေရန်၊ ခန့်မှန်းရန်နှင့် ပုံဖော်ရန် လက်တွေ့ကျသော နည်းလမ်း ၅ ခု။',
    feat_rocket_badge:'🚀 ပုံတူစမ်းသပ်မှု',feat_rocket_title:'ဒုံးပျံလွှတ်တင်မှု ပုံတူစမ်းသပ်စက်',feat_rocket_sub:'သင် ကမ္ဘာ့ပတ်လမ်းကြောင်းထဲကို ရောက်အောင် လွှတ်နိုင်မလား။',feat_rocket_desc:'တွန်းအား၊ လောင်စာ၊ ဝန်ဆောင်ခနှင့် လွှတ်တင်မည့် ထောင့်ချိုးတို့ကို သတ်မှတ်ပါ။ တကယ့် ဒုံးပျံရူပဗေဒအတိုင်း parameters တစ်ခုချင်းစီက သင့်ရဲ့ ခရီးလမ်းကြောင်းကို ပြောင်းလဲစေမှာပါ။',
    feat_city_badge:'🏙️ အသစ်',feat_city_title:'ရန်ကုန်မြို့ စွမ်းအင် ပုံတူစမ်းသပ်စက်',feat_city_sub:'မြို့တစ်မြို့ကို စွမ်းအင်ပေးပါ။ ကမ္ဘာမြေကို ကယ်တင်ပါ။',feat_city_desc:'ရန်ကုန်မြို့အတွက် အသင့်တော်ဆုံး စွမ်းအင်အရောအနှောကို ပုံဖော်ပါ။ ပြန်လည်ပြည့်ဖြိုးမြဲစွမ်းအင်နှင့် လောင်စာဆီတို့ကို မျှတအောင် ချိန်ညှိပြီး ညစ်ညမ်းမှု၊ မြို့ပြအပူရှိန်နှင့် လျှပ်စစ်ကွန်ရက်ခိုင်မာမှုတို့ တိုက်ရိုက်ပြောင်းလဲပုံကို ကြည့်ရှုလိုက်ပါ။',
    feat_explore:'လေ့လာရန်',feat_header:'✦ အထူးပြကွက်များ',feat_sub:'နက်နဲမှု၊ လှပမှုနှင့် လက်တွေ့စမ်းသပ်နိုင်မှုတို့အတွက် အသေအချာ ရွေးချယ်ထားပါသည်',
    feat_explore_subject:'ဘာသာရပ်အလိုက် လေ့လာရန်'
  },
  back:'← သို့ ပြန်သွားရန်',
  sec:{
    physics:{
      t:'ရူပဗေဒ',
      d:'ကျွန်ုပ်တို့စကြဝဠာရဲ့ အခြေခံအားများနှင့် တည်ဆောက်ပုံ အစိတ်အပိုင်းများကို လေ့လာလိုက်ပါ'
    },
    math:{
      t:'သင်္ချာ',
      d:'ကိန်းဂဏန်းများရဲ့ ပုံစံများ၊ သက်သေပြချက်များနှင့် ဝှက်ဖုံးနေသော တည်ဆောက်ပုံများကို ရှာဖွေလိုက်ပါ'
    },
    chemistry:{
      t:'ဓာတုဗေဒ',
      d:'အက်တမ်များမှသည် ဓာတ်ပြုမှုများအထိ — ဒြပ်ဝတ္ထုနှင့် ပြောင်းလဲမှုဆိုင်ရာ သိပ္ပံပညာ'
    },
    space:{
      t:'အကာသ',
      d:'နေအဖွဲ့အစည်း၊ ကြယ်များနှင့် စကြဝဠာအတွင်းသို့ ခရီးစဉ်'
    }
  },
  p_atom:{
    t:'အက်တမ် လေ့လာစူးစမ်းစက်',
    d:'ပရိုတွန်၊ နျူတွန်နှင့် အီလက်ထရွန်တို့ကို ပေါင်းထည့်ပြီး အက်တမ်များကို တည်ဆောက်ပါ။ မတူညီတဲ့ ဒြပ်စင်များကို ဖန်တီးပြီး အက်တမ်တည်ဆောက်ပုံက ဓာတုဗေဒအပေါ် ဘယ်လိုသက်ရောက်လဲဆိုတာ ကြည့်ရှုလိုက်ပါ။',
    tag:'အပြန်အလှန် မော်ဒယ်',
    protons:'ပရိုတွန်များ',
    neutrons:'နျူတွန်များ',
    electrons:'အီလက်ထရွန်များ',
    element:'ဒြပ်စင်',
    mass:'ဒြပ်ထုကိန်း',
    charge:'လျှပ်စစ်ဓာတ်ဆောင်မှု',
    neutral:'ဓာတ်မရှိ (ပလပ်မိုင်နပ်စ်မျှခြေ)',
    ion:'အိုင်းယွန်း (Ion)',
    shell:'အီလက်ထရွန်ပတ်လမ်းလွှာ',
    exp_t:'အက်တမ်များ မည်သို့အလုပ်လုပ်သနည်း',
    exp:'အက်တမ်တိုင်းမှာ ပရိုတွန် (+) နဲ့ နျူတွန် (၀) တွေနဲ့ ဖွဲ့စည်းထားတဲ့ <strong>နျူကလိယ (nucleus)</strong> ရှိပြီး ၎င်းကို အီလက်ထရွန် (-) တွေက ပတ်လမ်းကနေ ဝန်းရံထားပါတယ်။ ပရိုတွန်အရေအတွက်က ဒြပ်စင်ကို သတ်မှတ်တာပါ - ပရိုတွန် ၁ လုံးဆိုရင် ဟိုက်ဒရိုဂျင်၊ ၆ လုံးဆိုရင် ကာဗွန်၊ ၂၆ လုံးဆိုရင် သံ (Iron) ဖြစ်ပါတယ်။ အီလက်ထရွန်တွေကတော့ စွမ်းအင်အဆင့်အလိုက် ပတ်လမ်းလွှာတွေမှာ နေရာယူကြပါတယ်။'
  },
  p_forces:{
    t:'အားနှင့် ရွေ့လျားမှု',
    d:'ရွေ့လျားနေတဲ့ အရာဝတ္ထုတစ်ခုအပေါ် ဒြပ်ဆွဲအားနဲ့ ပွတ်တိုက်အားတွေက ဘယ်လိုသက်ရောက်လဲဆိုတာကို ချိန်ညှိကြည့်ပါ။ နယူတန်ရဲ့ ရွေ့လျားမှုနိယာမတွေကို လက်တွေ့စမ်းသပ် လေ့လာလိုက်ပါ။',
    tag:'ပုံစံတူ',
    mass:'ဒြပ်ထု',
    force:'သက်ရောက်အား',
    friction:'ပွတ်တိုက်အား',
    velocity:'အလျင်',
    accel:'အရှိန် (Acceleration)',
    reset:'ပြန်စမည်',
    exp_t:'နယူတန်၏ နိယာမများ',
    exp:'ပထမနိယာမ - အရာဝတ္ထုတွေဟာ ရွေ့လျားမှုအပြောင်းအလဲကို အစဉ်ခုခံကြတယ် (<strong>Inertia</strong>)။ ဒုတိယနိယာမ - <strong>F = ma</strong> (သက်ရောက်အားသည် ဒြပ်ထုနှင့် အရှိန်မြှောက်လဒ်နှင့် ညီမျှသည်)။ တတိယနိယာမ - သက်ရောက်မှုတိုင်းမှာ တူညီပြီး ဆန့်ကျင်ဘက်ဖြစ်တဲ့ တုံ့ပြန်မှုတစ်ခု အမြဲရှိပါတယ်။'
  },
  p_circuits:{
    t:'လျှပ်စစ်ပတ်လမ်း တည်ဆောက်စက်',
    d:'ဘက်ထရီ၊ ဝိုင်ယာကြိုးနှင့် မီးသီးများကို သုံးပြီး series နှင့် parallel circuits များကို တည်ဆောက်ပါ။ Ohm\'s Law ကို နားလည်စေရန် ဗို့အားနှင့် လျှပ်စီးကြောင်းကို တိုင်းတာကြည့်ပါ။',
    tag:'အပြန်အလှန်',
    voltage:'ဗို့အား (Voltage)',
    resistance:'ခုခံမှု (Resistance)',
    current:'လျှပ်စီးကြောင်း (Current)',
    power:'ပါဝါ (W)',
    exp_t:'အုမ်း၏ နိယာမ (Ohm\'s Law)',
    exp:'အုမ်းရဲ့နိယာမအရ <strong>V = I × R</strong> ဖြစ်ပါတယ်။ ဗို့အား (V) ဟာ လျှပ်စစ်ဖိအားဖြစ်ပြီး၊ လျှပ်စီးကြောင်း (I) ကတော့ လျှပ်စစ်ဓာတ်စီးဆင်းမှုဖြစ်ကာ ခုခံမှု (R) ကတော့ အဲဒီစီးဆင်းမှုကို ကန့်သတ်ပေးတာဖြစ်ပါတယ်။'
  },
  p_light:{
    t:'အလင်းနှင့် အရောင်',
    d:'မှန်ဘီလူးများနှင့် ပရစ်ဇင် (prisms) များကိုသုံးပြီး အလင်းကို ကွေ့ဝိုက်စေပါ။ အလင်းရဲ့ အခြေခံအရောင်များကို ပေါင်းစပ်ပြီး မျက်စိဖြင့်မြင်နိုင်သော ရောင်စဉ်တန်းများကို ဖန်တီးပါ။',
    tag:'အလင်းပညာ',
    focal:'အာရုံအကွာအဝေး',
    obj_dist:'အရာဝတ္ထု အကွာအဝေး',
    convex:'မျက်နှာပြင်အိုက် မှန်ဘီလူး',
    concave:'မျက်နှာပြင်ခွက် မှန်ဘီလူး',
    exp_t:'မှန်ဘီလူးနှင့် တယ်လီစကုပ်များ အလုပ်လုပ်ပုံ',
    exp:'<strong>Convex lens</strong> သည် အလင်းဆင်ဆင်ဆင်ဆင်များကို <strong>အာရုံမှတ် (focal point)</strong> တစ်ခုတွင် ဆုံမှတ်ပေးသည် — မှန်မြင်ကိရိယာ၊ ကင်မရာ၊ မျက်ချိုမှန်ဘီလူး ဤနည်းဖြင့် အလုပ်လုပ်သည်။ <strong>Concave lens</strong> မူ အလင်းကို ကွဲပြာစေသည်။ တယ်လီစကုပ်တွင် ကြီးသောအရာဝတ္ထုမှန်ဘီလူးသည် အလင်းများ ပိုမိုစုဆောင်းပြီး မျက်ဘောင်မှန်ဘီလူးငယ်က ချဲ့ပြသည်။ ရောင်ခြည်ပြိုကြားသည်မှာ ရေမှုန်များသည် မတူသော wavelength (အရောင်) များကို ကွဲပြားစွာ ကွဲဖြတ်သောကြောင့်ဖြစ်သည်။'
  },
  p_energy:{
    t:'စွမ်းအင်နှင့် လှိုင်းများ',
    d:'ချိတ်ဆွဲလှိုင်းဖြင့် အရွေ့နှင့် အနေ စွမ်းအင်ကို လေ့လာပါ။',
    tag:'ပုံစံတူ',
    ke:'အရွေ့စွမ်းအင်',
    pe:'အနေစွမ်းအင်',
    total:'စုစုပေါင်း',
    amp:'ပမာဏ',
    freq:'ကြိမ်နှုန်း',
    exp_t:'စွမ်းအင် ထိန်းသိမ်းမှု',
    exp:'စွမ်းအင်ကို ဖန်တီးလည်းမရ ဖျက်ဆီးလည်းမရ — ပုံသဏ္ဍာန်သာ ပြောင်းလဲနိုင်သည် (Conservation of Energy)။ ချောင်ဆွဲသည် အပေါ်ဆုံးတွင် <strong>ဆောင်ထားသောစွမ်းအင် (potential)</strong> အများဆုံးရှိပြီး အောက်ဆုံးတွင် <strong>လှုပ်ရှားမှုစွမ်းအင် (kinetic)</strong> အများဆုံးဖြစ်သည်။ ပူပြင်းမှုသည် မော်လီကျူးများ တုန်ခါမှုဖြစ်ပြီး လျှပ်စစ်သည် ဓာတ်ပြုမှုစွမ်းအင်ဖြစ်သည်။ နေ မှ အပင် မှ တိရိစ္ဆာန် မှ လူ — ဤသည် ပြောင်းလဲမှုဖြတ်သန်းလာသော စွမ်းအင်ဇာတ်လမ်းဖြစ်သည်။'
  },
  m_primes:{
    t:'ပရိုင်းကိန်း စစ်ထုတ်စက်',
    d:'Eratosthenes စစ်ထုတ်နည်းကို သုံးပြီး ပရိုင်းကိန်းများကို ရှာဖွေပါ။ ကိန်းတန်းပေါ်ရှိ ပရိုင်းကိန်းများ တည်ရှိပုံနှင့် ပဟေဠိများကို လေ့လာစူးစမ်းပါ။',
    tag:'အပြန်အလှန် ဂိမ်း',
    start:'စတင်',
    reset:'ပြန်စမည်',
    step:'အဆင့်',
    found:'တွေ့ရှိသော ဝိသေသကိန်း',
    checking:'စစ်ဆေးနေသည်',
    exp_t:'Eratosthenes ၏ စစ်ထုတ်နည်း',
    exp:'<strong>ဝိသေသကိန်း (prime)</strong> သည် ၁ နှင့် ကိုယ်တိုင်ဖြင့်သာ ဘောင်ကျသောကိန်းဖြစ်သည် — ဥပမာ ၂၊ ၃၊ ၅၊ ၇၊ ၁၁ ။ Eratosthenes ကင်ပွန်းဆန်ခါ (sieve) နည်းအရ ကိန်းများ တန်းစီပြပြီး ၂ မှ စတင်ကာ ၎င်း၏ ဆကိန်းများ ဖြတ်ပစ်သည် — ကျန်ရသောကိန်းများ ဝိသေသကိန်းများဖြစ်သည်။ ဝိသေသကိန်းများသည် <strong>RSA encryption</strong> (ဘဏ်ငွေလွှဲ၊ password ကာကွယ်ရေး) ၏ မူလဖြစ်ပြီး Euclid BC ၃ ရာစုတွင် ဝိသေသကိန်းများ အနန္တဖြစ်ကြောင်း သက်သေပြခဲ့သည်။'
  },
  m_fractals:{
    t:'ဖရက်တယ်လ် (Fractal) စူးစမ်းစက်',
    d:'သစ်ပင်တစ်ပင် အကိုင်းအခက်တွေ အဆုံးမဲ့ ခွဲထွက်သွားပုံကို ကြည့်ပါ။ ပြီးရင် Mandelbrot Set ထဲ ဝင်ကြည့်ပါ။ ရိုးရှင်းတဲ့ စည်းမျဉ်းတွေက အဆုံးမဲ့ ရှုပ်ထွေးမှုကို ဖန်တီးပါတယ်။',
    tag:'စူးစမ်းရှာဖွေမှု',
    tree:'ဖရက်တယ် သစ်ပင်',mandel:'Mandelbrot Set',depth:'အဆင့်',angle:'ထောင့်',ratio:'ကျုံ့နှုန်း',wind:'လေ',branches:'အကိုင်းအရေအတွက်',
    zoom:'ချုံ့/ချဲ့',
    detail:'အသေးစိတ်',
    reset:'ပြန်စမည်',
    coords:'သြဒီနိတ်',
    exp_t:'ဖရက်တယ်များ ဆိုတာ ဘာလဲ?',
    exp:'<strong>ဖရက်တယ် (fractal)</strong> သည် မည်သည့် ချဲ့မြင်နှုန်းဖြင့် ကြည့်ကြည့် တူညီသောပုံစံ ပြန်ပေါ်သောပုံသဏ္ဍာန် (self-similar) ဖြစ်သည်။ ဖရက်တယ် သစ်ပင်က ဒါကို လှလှပပ ပြသပေးပါတယ် — အကိုင်းတစ်ခုချင်းစီက ကိုယ့်ရဲ့ ပုံတူငယ်တွေ ခွဲထွက်သွားပါတယ်။ အဆင့်တိုးလေ ရှုပ်ထွေးမှု ပေါက်ကွဲလေ — ၁ ကိုင်းက ၂ ဖြစ်၊ ၄၊ ၈၊ ၁၆၊ ၃၂... အဆင့် ၁၃ မှာ ၈,၀၀၀ ကျော် ဖြစ်သွားပါတယ်! သဘာဝတွင် သစ်ပင်များ၊ ကမ်းနံပါးပုံသဏ္ဍာန်၊ နှင်းပွင့်များ၊ သွေးကြောများတွင်ပင် ဖရက်တယ်ပုံစံ တွေ့ရသည်။'
  },
  m_pythag:{
    t:'ဂျီသြမေတြီ ကစားကွင်း',
    d:'တြိဂံများ၊ စက်ဝိုင်းများနှင့် ပိုလီဂွန်များကို လက်တွေ့ကိုင်တွယ်ကြည့်ပါ။ ဧရိယာ၊ ထုထည်နှင့် ပိုက်သဂိုးရပ် သီအိုရီတို့ကို ပုံဖော်လေ့လာလိုက်ပါ။',
    tag:'အမြင်အာရုံ သက်သေ',
    side_a:'အနား a',
    side_b:'အနား b',
    hyp:'ထောင့်ဖြတ် c',
    exp_t:'a² + b² = c²',
    exp:'ထောင့်မှန်တြိဂံ မည်သည်မဆို a² + b² = c² ဖြစ်သည် — c သည် <strong>ထောင့်ဖြတ်အနား (hypotenuse)</strong> ဖြစ်ပြီး အရှည်ဆုံးအနားဖြစ်သည်။ ၃-၄-၅ Pythagorean triple ကို Babylon နှင့် Egypt ကများ BC ၂,၀၀၀ တွင် ဆောက်လုပ်ရေးအတွက် အသုံးပြုခဲ့ကြသည်။ GPS တည်နေရာ ရှာဖွေရာတွင်၊ ဆောက်လုပ်ရေးထောင့်မှန်စစ်ဆေးရာတွင်၊ ပစ်ချင်းသွားလမ်းတွက်ချက်ရာတွင် ယနေ့တိုင် အသုံးပြုနေသည်။ သက်သေပြပုံ ၃၇၀ ကျော် ရှိသောကြောင့် သင်္ချာသမိုင်းတွင် အများဆုံးသက်သေပြမှု ရသောပြဆိုချက်ဖြစ်သည်။'
  },
  m_prob:{
    t:'ဖြစ်နိုင်ခြေနှင့် စာရင်းအင်း',
    d:'အန်စာတုံးလှိမ့်ပြီး ကျပန်းမှုမှ ဖြစ်နိုင်ခြေ ဖြန့်ဝေမှုများ ပေါ်လာပုံကို ကြည့်ပါ။',
    tag:'အပြန်အလှန်',
    roll:'လှိမ့်!',
    rolls:'အကြိမ်ရေ',
    expected:'မျှော်မှန်း',
    actual:'အမှန်',
    coins:'ဒင်္ဂါး',
    dice:'အန်စာတုံး',
    exp_t:'ကိန်းကြီး ဥပဒေ',
    exp:'ကျပန်းဖြစ်ရပ်တစ်ခုကို ကြိုတင်ခန့်မှန်း၍မရသော်လည်း ကြိမ်ဖန်များစွာ ပြုလုပ်သောအခါ <strong>ကြီးသောဂဏန်းဥပဒေ (Law of Large Numbers)</strong> ဖြင့် ပုံမှန်ပုံစံ ပေါ်ပေါ်လာသည်။ ဆိုင်ရာ ၁ ကြိမ် ချပြောင်မှ မည်သည့်မျက်နှာမဆို ၁/၆ ဖြစ်နိုင်သည်။ ၁,၀၀၀ ကြိမ်ချပြောင်မှ တစ်မျက်နှာချင်း ~၁၆၇ ကြိမ် ကျသည်။ <strong>Bell Curve</strong> — လူ၏ အမြင့်၊ စစ်ဆေးမှတ်ထား — ပျမ်းမျှနှင့်အနားရှိသောဒေတာများ ဤပုံသဏ္ဍာန်နှင့် ကိုက်ညီကြသည်။'
  },
  m_trig:{
    t:'တြီဂိုနိုမေတြီ',
    d:'ယူနစ် စက်ဝိုင်းပေါ်တွင် sine, cosine, tangent ကို လေ့လာပါ။',
    tag:'အပြန်အလှန်',
    angle:'ထောင့်',
    sin:'sin',
    cos:'cos',
    tan:'tan',
    exp_t:'ယူနစ် စက်ဝိုင်း',
    exp:'အချင်းဝက် ၁ ရှိသောစက်ဝိုင်းပေါ် အမှတ်တစ်ခု ဖြတ်သန်းသောအခါ ၎င်း၏ x-ကိုဩဒိနိတ် = <strong>cosine</strong>၊ y-ကိုဩဒိနိတ် = <strong>sine</strong> ဖြစ်သည်။ ဤပုံစံ ပတ်ပတ်ရွေ့လျှင် <strong>လှိုင်းပုံသဏ္ဍာန် (wave)</strong> ဖြစ်ပြီး အသံ၊ အလင်း၊ ဒေသဆိုင်ရာ radio wave တိုင်းကို ဤနည်းဖြင့် ဖော်ပြနိုင်သည်။ <strong>Tangent</strong> = sin÷cos ဖြစ်ပြီး အဆောက်အဦ အမြင့်တိုင်းတာရာနှင့် ဘူမိဆိုင်ရာ မြေပုံချနိုင်ရေးတွင် အသုံးပြုသည်။'
  },
  c_ptable:{
    t:'ဒြပ်စင်အလှည့်ကျဇယား လေ့လာစူးစမ်းစက်',
    d:'ဒြပ်စင်များ၊ ၎င်းတို့ရဲ့ ဂုဏ်သတ္တိများနှင့် electron configurations များကို လေ့လာပါ။ အက်တမ်နံပါတ်အလိုက် ဇယားကို ဘယ်လိုစီစဉ်ထားသလဲဆိုတာ ကြည့်ရှုပါ။',
    tag:'ကိုးကား',
    anum:'အက်တမ်ဂဏန်း',
    sym:'သင်္ကေတ',
    name:'အမည်',
    amass:'အက်တမ်ဒြပ်ထု',
    cat:'အမျိုးအစား',
    exp_t:'ဒြပ်စင်အလှည့်ကျဇယား',
    exp:'Mendeleev သည် ဒြပ်စင်များကို အက်တမ်ဂဏန်းအလိုက် စီစဥ်ပြီး <strong>ကော်လံ (group)</strong> တူသောဒြပ်စင်များသည် ဓာတ်ပြုမှုသဘောတရားတူညီသည်ကို ရှာဖွေတွေ့ရှိခဲ့သည်။ ဘယ်ဖက်ကော်လံ alkali metals — ရေနှင့် ဓာတ်ပြုသောအခါ ဝင်ရောင်တတ်သည်။ ညာဖက်ကော်လံ Noble gases မည်သောဒြပ်စင်နှင့်မျှ ဓာတ်မပေါင်းဘဲ တည်ငြိမ်သည်။ ၁၈၆၉ ခုနှစ်တွင် Mendeleev မတွေ့ရသေးသောဒြပ်စင်များကို ကြိုတင်ခန့်မှန်းနိုင်ခဲ့ပြီး နောင်တွင် တွေ့ရှိခဲ့သည်။'
  },
  c_states:{
    t:'ဒြပ်ဝတ္ထု အခြေအနေများ',
    d:'အပူချိန်ကို ထိန်းချုပ်ပြီး အမှုန်များ ပြောင်းလဲပုံကို ကြည့်ပါ။',
    tag:'အမှုန် ပုံစံတူ',
    temp:'အပူချိန်',
    solid:'အစိုင်အခဲ',
    liquid:'အရည်',
    gas:'ဓာတ်ငွေ့',
    exp_t:'အရွေ့ မော်လီကျူး သီအိုရီ',
    exp:'ဒြပ်ဝတ္ထုသည် အမြဲတမ်းရွေ့လျားနေသောမော်လီကျူးများဖြင့် ဖွဲ့စည်းသည်။ <strong>အစိုင် (solid)</strong> — မော်လီကျူးများ တင်းကျပ်စွာ ကပ်ပြီး နေရာကျ တုန်ခါသည်။ <strong>အရည် (liquid)</strong> — ချောချောမွေ့မွေ့ ရွေ့ပြောင်းနိုင်ပြီး ပုံသဏ္ဍာန်ပြောင်းနိုင်သော်လည်း ထုထည်တူသည်။ <strong>ဓာတ်ငွေ့ (gas)</strong> — မော်လီကျူးများ လွတ်လပ်စွာ ပြေးပြီး ပုံသဏ္ဍာန်နှင့် ထုထည်နှစ်ရပ်လုံး ပြောင်းနိုင်သည်။ <strong>ပလာစမာ (plasma)</strong> — ပူပြင်းလွန်းသောကြောင့် အက်တမ်ကွဲကျပြီး နေ (Sun) နှင့် မိုးကြိုးပစ်တွင် ဤပုံစံ ဖြစ်ပေါ်သည်။'
  },
  c_bonds:{
    t:'မော်လီကျူး ပေါင်းစည်းမှုများ',
    d:'အက်တမ်များကို ပေါင်းစပ်ပြီး covalent နှင့် ionic bonds များကို ဖန်တီးပါ။ ရေနှင့် ကာဗွန်ဒိုင်အောက်ဆိုက်ကဲ့သို့ မော်လီကျူးများကို တည်ဆောက်ပြီး ၎င်းတို့ရဲ့ 3D တည်ဆောက်ပုံကို ကြည့်ရှုပါ။',
    tag:'အပြန်အလှန်',
    ionic:'အိုင်းယွန်းနစ် (Ionic)',
    covalent:'ကိုဗေးလင့် (Covalent)',
    transfer:'အီလက်ထရွန်များ လွှဲပြောင်းပေးခြင်း',
    share:'အီလက်ထရွန်များ မျှဝေခြင်း',
    exp_t:'ဓာတုပေါင်းစည်းမှုများ',
    exp:'အက်တမ်တွေဟာ ပိုပြီးတည်ငြိမ်ဖို့အတွက် ပေါင်းစည်းကြပါတယ်။ အက်တမ်တွေ အီလက်ထရွန် မျှဝေသုံးစွဲတဲ့အခါ <strong>ကိုဗေးလင့် ပေါင်းစည်းမှု (Covalent bonds)</strong> ဖြစ်လာပါတယ် (ဥပမာ- ရေ)။ အက်တမ်တစ်ခုက နောက်တစ်ခုကို အီလက်ထရွန် လွှဲပြောင်းပေးပြီး ဆွဲဆောင်မှုဖြစ်လာတဲ့အခါ <strong>အိုင်းယွန်းနစ် ပေါင်းစည်းမှု (Ionic bonds)</strong> ဖြစ်လာပါတယ် (ဥပမာ- ဆား)။'
  },
  c_ph:{
    t:'pH Scale ဓာတ်ခွဲခန်း',
    d:'နေ့စဉ်သုံးပစ္စည်းများရဲ့ အက်ဆစ်ဓာတ်နှင့် ဘေ့စ်ဓာတ်များကို စမ်းသပ်ပါ။ Indicators များကို သုံးပြီး အရည်ဖျော်လိုက်တဲ့အခါ pH အဆင့်တွေ ဘယ်လိုပြောင်းလဲသွားသလဲဆိုတာ ကြည့်ရှုပါ။',
    tag:'အပြန်အလှန်',
    acidic:'အက်ဆစ်ဓာတ်',
    neutral:'ကြားနေ',
    basic:'ဘေ့ဆစ်ဓာတ်',
    ph:'pH အဆင့်',
    exp_t:'pH စကေး',
    exp:'pH သည် ဟိုက်ဒရိုဂျင် အိုင်ယွန် (H⁺) ပမာဏကို ၀ မှ ၁၄ ကြားဖြင့် တိုင်းတာသည်။ <strong>pH < 7 (acid)</strong> — ဝမ်းဗိုက်ရည်၊ ဆပ်ရည်၊ ကော်ဖီ ဤပုံစံဖြစ်သည်။ <strong>pH > 7 (base)</strong> — ဆပ်ပြာ၊ ဘေကင်ဆိုဒါ ဤပုံစံဖြစ်သည်။ <strong>pH = 7</strong> — သန့်ရှင်းသောရေ ကြားနေ။ ဆေးကုသ၊ စိုက်ပျိုးရေး၊ သတ္တုဓာတ်ဆားထုတ်လုပ်ရေးတို့တွင် pH ထိန်းချုပ်ရေး အရေးကြီးသည်။'
  },
  c_react:{
    t:'ဓာတုဓာတ်ပြုမှုများ',
    d:'ဓာတုဓာတ်ပြုမှုတွေဖြစ်လာဖို့ ဓာတ်ကူပစ္စည်းများကို ရောစပ်ပါ။ အပူစုပ်ယူမှုနှင့် အပူထုတ်လွှတ်မှု ဖြစ်စဉ်များကို လေ့လာပြီး ဓာတုညီမျှခြင်းများကို ချိန်ညှိပါ။',
    tag:'ပဟေဋ္ဌိ ဂိမ်း',
    balanced:'ချိန်ညှိပြီး!',
    notyet:'မချိန်ညှိရသေး',
    check:'စစ်ဆေး',
    next:'နောက်တစ်ခု',
    exp_t:'ဒြပ်ထု ထိန်းသိမ်းမှု',
    exp:'ဓာတ်ပြုမှုတိုင်းတွင် အက်တမ်များ ပြန်စီစဥ်ရုံသာ — ဖန်တီးခြင်း/ဖျက်ဆီးခြင်း မပြုနိုင်။'
  },
  s_solar:{
    t:'နေအဖွဲ့အစည်း ပုံစံတူ',
    d:'ကျွန်ုပ်တို့ နေအဖွဲ့အစည်းထဲက ဂြိုဟ်များ၊ လများနှင့် ဂြိုဟ်သိမ်ဂြိုဟ်မွှားများကို လေ့လာပါ။ ဤပုံစံတူအတွင်း ဂြိုဟ်များရဲ့ အရွယ်အစားနှင့် ပတ်လမ်းကြောင်းကြာချိန်များကို နှိုင်းယှဉ်ကြည့်ပါ။',
    tag:'စူးစမ်းရှာဖွေမှု',
    speed:'အချိန် အမြန်နှုန်း',
    dist:'နေမှ အကွာအဝေး',
    diam:'အချင်း',
    moons:'လများ',
    day:'တစ်ရက် အရှည်',
    year:'တစ်နှစ် အရှည်',
    exp_t:'ကျွန်ုပ်တို့၏ နေအဖွဲ့အစည်း',
    exp:'ဂြိုလ် ၈ လုံးသည် <strong>ဆွဲငင်အား (gravity)</strong> ကြောင့် နေ (Sun) ကို ပတ်ဝန်းကင်းပတ်နေသည်။ <strong>ကျောက်ဂြိုလ်များ</strong> Mercury, Venus, Earth, Mars — ငယ်ပြီး ဆင်ဆင်ဆင်နစ်ဖြစ်သည်။ <strong>ဓာတ်ငွေ့ပင်မကြီး (gas giants)</strong> Jupiter, Saturn, Uranus, Neptune — ကြီးမားသည်။ ကမ္ဘာသည် <strong>နေနွေးကွင်း (habitable zone)</strong> တွင် တည်ရှိပြီး ရေ အရည်ဖြစ်နိုင်သောကြောင့် သက်ရှိများ ဖြစ်ပေါ်နိုင်သည်။'
  },
  s_rocket:{
    t:'ဒုံးပျံလွှတ်တင်မှု ပုံတူစမ်းသပ်စက်',
    d:'အင်ဂျင်၊ တွန်းအား၊ လောင်စာ၊ ကုန်ရွေးနှင့် အဆင့်များကို ချိန်ညှိပါ။ လကို ရောက်ဖို့ အကောင်းဆုံး ဒီဇိုင်းကို ရှာပါ!',
    tag:'ရူပဗေဒ ဂိမ်း',
    thrust:'တွန်းအား',
    angle:'လွှတ်တင်ထောင့်',
    fuel:'လောင်စာ',
    payload:'ကုန်ရွေး',
    alt:'အမြင့် (km)',
    vel:'အလျင် (m/s)',
    launch:'လွှတ်တင်!',
    reset:'ပြန်စမည်',
    orbit:'ပတ်လမ်း ပစ်မှတ်',
    engine:'အင်ဂျင်',
    stages:'အဆင့်',
    mass:'ဒြပ်ထု',
    twr:'TWR',
    dv:'Δv ဘတ်ဂျက်',
    predict:'ခန့်မှန်းချက်',
    mission:'မစ်ရှင် ထိန်းချုပ်ခန်း',
    optimize:'လကိုရောက်ဖို့ ချိန်ညှိပါ 🌕',
    kerosene:'ဒီဇယ်/LOX',
    hydrogen:'ဟိုက်ဒရိုဂျင်/LOX',
    methane:'မီသိန်း/LOX',
    eng_hint:'ISP',stg_hint:'အလေးချိန် ချပါ',thr_hint:'↑TWR',fuel_hint:'↑Δv ↑ဒြပ်ထု',pay_hint:'↑ဒြပ်ထု ↓Δv',ang_hint:'လွှတ်ထောင့်',
    auto_adj:'အလိုအလျောက် ချိန်ညှိပြီး',
    exp_t:'ဒုံးပျံ သိပ္ပံ',
    exp:'ဒုံးပျံများသည် နယူတန်တတိယဥပဒေ (ကြိုးဆွဲ = တန်ပြန်ကြိုးဆွဲ) ဖြင့် မြင့်တက်သည်။ <strong>Thrust-to-Weight Ratio (TWR)</strong> သည် ၁.၀ ကျော်မှသာ ဂြိုလ်ဆွဲအားကို ကျော်လွှားနိုင်သည်။ ဓာတ်ဆီ ပိုသွင်းလျှင် ဒြပ်ထု ကြီးသောကြောင့် TWR ကျသည် — ဤသည်ပင် ပိုသွင်းများ-ပိုသွင်းမကောင်းဟူသောပြဿနာဖြစ်သည်။ လ (Moon) ရောက်ရန် ကမ္ဘာ orbit မှ Trans-Lunar Injection (TLI) burn ထပ်မံ လုပ်ဆောင်ပြီး ~384,400 km ခရီး သွားနိုင်ရမည်။'
  },
  s_moon:{
    t:'လ အဆင့်များ',
    d:'လကို ကမ္ဘာပတ်လည် ဆွဲယူပြီး အဆင့်များ ပြောင်းလဲပုံကို ကြည့်ပါ။',
    tag:'အပြန်အလှန် မော်ဒယ်',
    phase:'လက်ရှိ အဆင့်',
    new:'လကွယ်',
    waxc:'လသစ်',
    firstq:'ပထမ သုံးပုံ',
    waxg:'လဝက်ကျော်',
    full:'လပြည့်',
    wang:'လဝက်ကျော်ဆုတ်',
    lastq:'နောက်ဆုံး သုံးပုံ',
    wanc:'လကွယ်နီး',
    exp_t:'လ ဘာကြောင့် အဆင့်ရှိသနည်း',
    exp:'လ (Moon) သည် မိမိပိုင် အလင်းမထုတ် — နေ (Sun) ၏ အလင်းကို ပြန်ဟပ်သည်။ ကမ္ဘာပတ်ဝန်းကင်း ~၂၉.၅ ရက်ကြာသောကြောင့် ကျွန်ုပ်တို့ မြင်သောလပြင်ငုတ် ပြောင်းလဲသည်။ <strong>လမြင်မရပြ (New Moon)</strong> — မမြင်ရ။ <strong>လပြည့် (Full Moon)</strong> — အပြည့်မြင်ရ။ <strong>ကမ်းတက်ကမ်းဆင်း (tide)</strong> ဖြစ်ရပ်သည် လ၏ ဆွဲငင်အားကြောင့် ပင်လယ်ကမ်းတွင် ရေ ထ/ဆင်း ဖြစ်ပေါ်သည်။'
  },
  s_star:{
    t:'ကြယ်တစ်လုံးရဲ့ ဘဝသံသရာ',
    d:'ကြယ်တစ်လုံးရဲ့ နက်ဗျူလာမှသည် စူပါနိုဗာ သို့မဟုတ် black hole အထိ ခရီးစဉ်ကို လေ့လာပါ။ ဒြပ်ထုက ကြယ်တစ်လုံးရဲ့ နောက်ဆုံးကံကြမ္မာကို ဘယ်လိုဆုံးဖြတ်သလဲဆိုတာ ရှာဖွေပါ။',
    tag:'အမြင်အာရုံ ခရီး',
    nebula:'နက်ဗျူလာ (Nebula)',
    protostar:'ပရိုတိုကြယ်',
    mainseq:'ပုံမှန်သက်တမ်း (Main Sequence)',
    redgiant:'ကြယ်နီကြီး (Red Giant)',
    supernova:'စူပါနိုဗာ (Supernova)',
    neutron:'နျူထရွန် ကြယ်',
    blackhole:'Black Hole',
    whitedwarf:'ကြယ်ဖြူပု (White Dwarf)',
    exp_t:'ကြယ်များ၏ ဖြစ်တည်မှုနှင့် ပြောင်းလဲမှု',
    exp:'ကြယ်တစ်လုံးရဲ့ ဘဝဆိုတာ <strong>ဒြပ်ဆွဲအား</strong> (အတွင်းသို့ဆွဲခြင်း) နဲ့ <strong>နျူကလီးယား ပေါင်းစပ်မှု</strong> (အပြင်သို့တွန်းခြင်း) တို့ကြားက တိုက်ပွဲပါပဲ။ သေးငယ်တဲ့ ကြယ်တွေက ကြယ်ဖြူပုတွေအဖြစ် ဘဝဆုံးကြပါတယ်။ ကြီးမားတဲ့ ကြယ်တွေကတော့ စူပါနိုဗာအဖြစ် ပေါက်ကွဲသွားပြီး နျူထရွန်ကြယ်တွေ ဒါမှမဟုတ် Black Hole တွေ ကျန်ရစ်ခဲ့ပါတယ်။'
  },
  s_tele:{
    t:'တယ်လီစကုပ် အလုပ်လုပ်ပုံ',
    d:'အကွာဝေးရှိ အရာဝတ္ထုများကို မြင်ရန် တယ်လီစကုပ်များ အလင်းစုဆောင်းပုံကို ကြည့်ပါ။',
    tag:'အလင်းပညာ',
    refract:'အလင်းကွေ့',
    reflect:'အလင်းရောင်ပြန်',
    aperture:'အဝင်ဝ',
    mag:'ချဲ့ကြည့်မှု',
    exp_t:'တယ်လီစကုပ်များ: မမြင်နိုင်သည်ကို မြင်ခြင်း',
    exp:'<strong>မှန်ဘီလူးတယ်လီစကုပ် (Refracting)</strong> သည် မှန်ဘီလူးများ အသုံးပြုပြီး ဝေးကွာသောပစ်မှတ်ကို ချဲ့ပြသည် — Galileo ၁၆၀၉ ခုနှစ်တွင် ပထမဆုံး သုံးပြုခဲ့သည်။ <strong>မှောင်မှန်ကြောင်တယ်လီစကုပ် (Reflecting)</strong> သည် concave mirror ကို သုံးပြီး ပိုကြီးသော aperture ရနိုင်သည် — Newton ၁၆၆၈ ခုနှစ်တွင် ပထမ ဖန်တီးခဲ့သည်။ Aperture ကြီးလေ အလင်းပိုစုဆောင်းလေ ဝေးကွာသောဂဟဆာဂလပ်စီများ မြင်နိုင်လေဖြစ်သည်။ Hubble Space Telescope သည် ကမ္ဘာ orbit မှ Universe ကို ၁၃.၈ billion years နောက်ကြောင်းပြန် မြင်ရစေသည်。'
  },
  pi:{
    t:'Pi Day အထူးပြပွဲ: π ၏ အံ့ဖွယ်ကမ္ဘာ',
    d:'Pi Day (မတ်လ ၁၄ ရက် = 3.14) ကို အပြန်အလှန်တုံ့ပြန်နိုင်သော နည်းလမ်း ၅ မျိုးဖြင့် သင်္ချာလောကရဲ့ အကျော်ကြားဆုံးကိန်း π ကို ရှာဖွေ၊ မြင်သာအောင်ပြသ၊ ခန့်မှန်းတွက်ချက်ကြည့်ပါ။',
    tag:'အထူးပြပွဲ',
    banner:'Pi Day ပျော်ရွှင်ပါစေ! မတ်လ ၁၄ ရက် = 3.14 = π',
    tab_monte:'မွန်တီကာလို နည်း',
    tab_buffon:'ဗူဖွန်၏ အပ်ချောင်း',
    tab_digits:'π ဂဏန်းများ',
    tab_leibniz:'လိုက်ဗ်နစ် အစဉ်',
    tab_circle:'C ÷ d = π',
    monte_title:'ကျပန်းအမှတ်များ ကျဲချ၍ π ကို ခန့်မှန်းကြည့်ပါ',
    monte_info:'စတုရန်းပုံအတွင်း ထည့်သွင်းထားသော စက်ဝိုင်းထဲသို့ ကျပန်းအမှတ်များ ကျဲချပါ။ စက်ဝိုင်းအတွင်းကျသော အမှတ်အရေအတွက်နှင့် စုစုပေါင်းအမှတ်အရေအတွက်၏ အချိုးသည် π/4 နှင့် ညီပါသည်။ အမှတ်များများ ကျဲလေ တိကျလေဖြစ်သည်!',
    inside_circle:'စက်ဝိုင်းအတွင်း',
    total_points:'စုစုပေါင်း အမှတ်ရေ',
    error:'ကွာဟချက်',
    start_rain:'စတင်ကျဲချရန်',
    stop_rain:'ရပ်တန့်',
    buffon_title:'ဗူဖွန်၏ အပ်ချောင်း ပြဿနာ (၁၇၇၇)',
    buffon_info:'အပြိုင်မျဉ်းများပေါ်သို့ အပ်ချောင်းများ ကျဲချပါ။ မျဉ်းကိုဖြတ်ကျော်သော အပ်ချောင်းအရေအတွက်၏ အချိုးကို အသုံးပြု၍ π ကို ခန့်မှန်းနိုင်ပါသည်!',
    needles_dropped:'အပ်ချောင်းရေ',
    crossing:'မျဉ်းဖြတ်ကျော်',
    drop_needles:'အပ်ချောင်းများ ကျဲချပါ',
    digits_title:'π ၏ ပထမဆုံး ဂဏန်းတစ်ထောင်',
    digits_info:'ဂဏန်း 0 မှ 9 အထိ တစ်ခုချင်းစီကို အရောင်ကွဲပြား၍ ခွဲခြားပြထားသည်။ π ၏ ဒဿမဂဏန်းများသည် ကျပန်းပုံစံဖြစ်ပြီး ယနေ့တိုင် မည်သူမျှ ပုံစံတစ်ခုမှ ရှာမတွေ့သေးပါ!',
    showing:'ပြသနေသည်',
    digits_of_pi:'π ဒဿမဂဏန်းများ',
    freq_title:'ဂဏန်းအလိုက် ပေါ်နှုန်းဖြန့်ကြက်ပုံ',
    freq_info:'အမှန်တကယ် ကျပန်းဖြစ်သော ဂဏန်းအစဉ်တွင် ဂဏန်းတစ်လုံးချင်းစီ 10% စီ ပေါ်လာသင့်ပါသည်။ π ၏ ဂဏန်းများသည် ထိုအချိုးနှင့် အလွန်နီးစပ်ပါသည်!',
    leibniz_title:'လိုက်ဗ်နစ် အစဉ် — အဆုံးမဲ့ ပေါင်းလဒ်မှ π သို့',
    leibniz_info:'π/4 = 1 - 1/3 + 1/5 - 1/7 + ... ဤအဆုံးမဲ့ကိန်းစဉ်သည် π တန်ဖိုးသို့ တဖြည်းဖြည်း ချဉ်းကပ်သွားပုံကို လက်တွေ့ကြည့်ရှုလိုက်ပါ — လှပသော်လည်း အလွန်နှေးကွေးသော ချဉ်းကပ်မှုဖြစ်သည်!',
    terms:'ကိန်းလုံးရေ',
    current_sum:'လက်ရှိ ခန့်မှန်းတန်ဖိုး',
    animate:'လှုပ်ရှားပြသ',
    circle_title:'လုံးပတ် ÷ အချင်း = π (အမြဲတမ်းမှန်ကန်သည်!)',
    circle_info:'စက်ဝိုင်းတစ်ခုကို မျဉ်းဖြောင့်တစ်ကြောင်းပေါ်တွင် လှိမ့်ကြည့်ပါ။ တစ်ပတ်အပြည့် လှိမ့်လိုက်သောအခါ ရွေ့သွားသော အကွာအဝေးသည် π × အချင်း နှင့် အတိအကျ ညီပါသည်။ ဤသည်မှာ π ၏ မူလအဓိပ္ပာယ်ဖွင့်ဆိုချက် ဖြစ်ပါသည်!',
    radius:'အချင်းဝက်',
    roll_circle:'စက်ဝိုင်းလှိမ့်ကြည့်ပါ',
    revolutions:'ပတ်ရေ',
    distance:'ရွေ့သွားသော အကွာအဝေး',
    exp_t:'Pi (π) ၏ အံ့ဖွယ်ကမ္ဘာ',
    exp:'<strong>Pi (π ≈ 3.14159...)</strong> သည် စက်ဝိုင်း၏ လုံးပတ်ကို အချင်းဖြင့် စားလိုက်လျှင် ရရှိသော အချိုးဖြစ်ပြီး သင်္ချာနှင့် သဘာဝလောကတစ်ခုလုံးတွင် အံ့ဖွယ်ရာ နေရာအနှံ့ ပေါ်လာပါသည်။ π သည် <strong>အပြည့်ကိန်းအချိုးဖြင့် မဖော်ပြနိုင်သော ကိန်း (irrational)</strong> ဖြစ်ပြီး ဒဿမများ အဆုံးမရှိ ဆက်သွားကာ ထပ်ခါထပ်ခါ ပြန်မလာပါ။ ဖြစ်နိုင်ခြေ သီအိုရီ (Buffon ၏ အပ်ချောင်း)၊ အဆုံးမဲ့ကိန်းစဉ်များ (Leibniz, Euler)၊ ကွမ်တမ်ရူပဗေဒ၊ အထွေထွေနှိုင်းယှဉ်ရူပဗေဒနှင့် ဝိသေသကိန်းများ၏ ဖြန့်ကြက်ပုံတို့တွင်ပင် π ပေါ်လာပါသည်။ မတ်လ ၁၄ ရက် (3/14) ကို ကမ္ဘာတစ်ဝှမ်း Pi Day အဖြစ် ဆင်နွှဲကျင်းပကြပါသည် — အိုင်းစတိုင်း၏ မွေးနေ့လည်း ဖြစ်ပါသေးသည်!'
  },
  riemann:{
    t:'ရီမန် ဇီတာ ဖန်ရှင်',
    d:'သင်္ချာလောက၏ အနက်နဲဆုံး မဖြေရှင်းနိုင်သေးသော ပြဿနာကို လေ့လာပါ — ဇီတာဖန်ရှင်၏ သုညများသည် ဝိသေသကိန်းများ၏ ပုံစံကို မည်သို့ ကုဒ်လုပ်ထားသနည်း။',
    tag:'အဆင့်မြင့် အပြန်အလှန်',
    tab1:'အရေးပါသော မျဉ်း',
    tab2:'ဝိသေသကိန်း လှေကားထစ်',
    tab3:'ကြီးမြတ်သော ဆက်စပ်မှု',
    cl_title:'အရေးပါသော မျဉ်းပေါ်ရှိ သုညများ',
    cl_info:'ပြထားသော သုည ၃၀ လုံးအားလုံး Re(s)=½ မျဉ်းပေါ်တွင် တည်ရှိသည်။ ရီမန် ယူဆချက်အရ သုညအားလုံး ဤနေရာတွင် တည်ရှိသည်ဟု ခန့်မှန်းထားသည်။',
    strip:'အရေးပါသော ကန့်လန့်ဖြတ်',
    cline:'အရေးပါသော မျဉ်း Re=½',
    zeros_lbl:'သုညများ',
    showing_n:'ပထမ {n} သုညများ ပြသနေသည်',
    ps_title:'ဝိသေသကိန်း ရေတွက်ဖန်ရှင် π(x) နှင့် Li(x)',
    ps_info:'လှေကားထစ် π(x) သည် x အထိ ဝိသေသကိန်းများကို ရေတွက်သည်။ ချောမွေ့သော Li(x) မျဉ်းကွေးသည် ကောင်းမွန်သော ခန့်မှန်းချက်ဖြစ်သည်။',
    x_range:'x အပိုင်းအခြား',
    prime_count:'ဝိသေသကိန်း ရေတွက်',
    li_approx:'log ပေါင်းစုခန့်မှန်း',
    error_lbl:'ကွာဟချက်',
    gc_title:'သုညများ ဝိသေသကိန်းများကို ပုံဖော်ပုံ',
    gc_info:'သုညများကို တစ်ခုချင်း ထည့်ပြီး ချောမွေ့သော Li(x) မျဉ်းကွေးတွင် ဝိသေသကိန်း လှေကားထစ်နှင့် ကိုက်ညီသော လှိုင်းများ ဖြစ်ပေါ်လာပုံကို ကြည့်ပါ။',
    num_zeros:'အသုံးပြုသော သုည',
    zeros_used:'အရေးပါသော မျဉ်းမှ သုည {n} ခု',
    zeros_word:'သုည',
    actual:'အမှန်တကယ် ဝိသေသကိန်း',
    smooth:'ချောမွေ့ (သုညမပါ)',
    recon:'ပြန်လည်တည်ဆောက်',
    hint0:'Li(x) တစ်ခုတည်းသည် ချောမွေ့သည် — လှေကားထစ်များကို လွဲချော်နေသည်',
    hint_few:'သုည အနည်းငယ်ဖြင့် ဝိသေသကိန်း လှေကားထစ်ဆီသို့ လှိုင်းများ စတင်ဖြစ်ပေါ်နေသည်...',
    hint_mid:'ပြန်လည်တည်ဆောက်မှုသည် ဝိသေသကိန်းများတွင် ခုန်တက်မှုများနှင့် ပိုမိုကိုက်ညီလာသည်!',
    hint_many:'သုည အများအပြားဖြင့် ပြန်လည်တည်ဆောက်မှုသည် π(x) ကို နီးကပ်စွာ လိုက်နေသည် — သုညများသည် ဝိသေသကိန်းများကို ကုဒ်လုပ်ထားသည်!',
    axis_x:'x',
    exp_t:'ရီမန် ယူဆချက်',
    exp:'<strong>ရီမန် ဇီတာ ဖန်ရှင် ζ(s)</strong> သည် ကွန်ပလက်စ် ခွဲခြမ်းစိတ်ဖြာမှု လောကနှင့် ဝိသေသကိန်းများကို ဆက်စပ်ပေးသည်။ ရီမန်သည် ζ(s) ၏ <strong>သုညများ</strong>တွင် ဝိသေသကိန်းများ ဖြန့်ကြက်ပုံအကြောင်း တိကျသော သတင်းအချက်အလက် ပါဝင်ကြောင်း ရှာဖွေတွေ့ရှိခဲ့သည်။ သုညအားလုံး၏ real part သည် အတိအကျ ½ ဖြစ်သည်ဟူသော ၎င်း၏ ယူဆချက်သည် နှစ် ၁၆၀ ကျော်ကြာပြီး မသက်သေပြနိုင်သေးဘဲ Millennium Prize ဒေါ်လာ ၁ သန်း ဆုချီးမြှင့်ထားသည်။'
  },
  city:{
    t:'ရန်ကုန်မြို့ စွမ်းအင်အသုံးပြုမှု စီမံခန့်ခွဲခြင်း',
    d:'ရန်ကုန်မြို့အတွက် အကောင်းဆုံး စွမ်းအင်ပေါင်းစပ်မှုကို ဒီဇိုင်းဆွဲပါ။ ကျောက်မီးသွေး၊ သဘာဝဓာတ်ငွေ့၊ နေရောင်ခြည်၊ လေအား၊ ရေအားစွမ်းအင်တို့ကို ချိန်ညှိ၍ ကာဗွန်ထုတ်လွှတ်မှု၊ လေထုအရည်အသွေး၊ အပူကျွန်းသက်ရောက်မှုနှင့် ဓာတ်အားကွန်ယက် ယုံကြည်စိတ်ချရမှုတို့ကို လက်တွေ့ကြည့်ပါ။',
    tag:'စီမံခန့်ခွဲမှု ဂိမ်း',
    energy_mix:'စွမ်းအင် ပေါင်းစပ်မှု',
    green_space:'စိမ်းလန်းသော နေရာ',
    hour:'နေ့အချိန်',
    day_cycle:'နေ့စဉ်သံသရာ',
    pause:'ခဏရပ်',
    metrics:'မြို့ကြီး အညွှန်းကိန်းများ',
    emissions:'ကာဗွန်ထုတ်လွှတ်မှု',
    air_quality:'လေထု အရည်အသွေး',
    reliability:'ဓာတ်အားကွန်ယက် ယုံကြည်စိတ်ချရမှု',
    heat_island:'အပူကျွန်း သက်ရောက်မှု',
    renew_pct:'ပြန်လည်ပြည့်ဖြိုးနိုင်စွမ်း %',
    cost:'ပျမ်းမျှ ကုန်ကျစရိတ်',
    daily_reliability:'၂၄ နာရီ ယုံကြည်စိတ်ချရမှု ပရိုဖိုင်',
    verdict_excellent:'စံပြ စိမ်းလန်းမြို့! သန့်ရှင်းသောလေ၊ ယုံကြည်ရသော ဓာတ်အား၊ အေးမြသောလမ်းများ။',
    verdict_good:'တိုးတက်မှုကောင်း! မြို့သည် ရေရှည်တည်တံ့မှုဆီသို့ ဦးတည်နေသည်။',
    verdict_moderate:'အသင့်အတင့် — ကာဗွန်ထုတ်လွှတ်မှု သို့ ယုံကြည်ရမှုတွင် တိုးတက်ရန် လိုအပ်သည်။',
    verdict_poor:'အရေးကြီး ညစ်ညမ်းမှုအဆင့်! လောင်စာကျောက်ဖြစ် မှီခိုမှု မြို့ကို ထိခိုက်နေသည်။',
    advice_reliability:'⚡ ဓာတ်အားကွန်ယက် အားနည်းနေသည်။ ပြန်လည်ပြည့်ဖြိုးနိုင်စွမ်းအင်များအတွက် ညဘက် လိုအပ်ချိန်တွင် ဓာတ်ငွေ့ သို့ ရေအား အရန်ထားရန် လိုအပ်သည်။',
    advice_carbon:'🏭 CO₂ ထုတ်လွှတ်မှု အလွန်မြင့်နေသည်။ ကျောက်မီးသွေးကို လျှော့၍ နေရောင်ခြည်/လေအား တိုးပါ။',
    advice_heat:'🌡️ မြို့အပူကျွန်း ပြင်းထန်နေသည်။ စိမ်းလန်းနေရာ တိုးပြီး လောင်စာကျောက်ဖြစ် လျှော့ပါ။',
    advice_perfect:'🌍 ထူးချွန်ပါသည်! သန့်ရှင်းလေ၊ ယုံကြည်ရသောဓာတ်အား၊ အေးမြသောလမ်းများ — ဤသည် ရေရှည်တည်တံ့သော မြို့ပြစွမ်းအင်ပုံစံ ဖြစ်သည်။',
    advice_balance:'💡 ပြန်လည်ပြည့်ဖြိုးနိုင်စွမ်းအင်နှင့် ထိန်းချုပ်နိုင်သော အရင်းအမြစ်များ ချိန်ညှိကြည့်ပါ။ နေရောင်ခြည်သည် မွန်းတည့်ချိန် အထွတ်အထိပ်ဖြစ်ပြီး ညဘက် သုညဖြစ်သည် — ရေအား သို့ ဓာတ်ငွေ့ဖြင့် တွဲဖက်ပါ။',
    exp_t:'မြို့ပြ စွမ်းအင်နှင့် ရာသီဥတု သိပ္ပံ',
    exp:'မြို့ကြီးများသည် ကမ္ဘာ့စွမ်းအင် ၇၅% ကျော် သုံးစွဲပြီး CO₂ ၇၀% ထုတ်လွှတ်သည်။ <strong>စွမ်းအင်ပေါင်းစပ်မှု</strong> — မြို့ကို ဓာတ်အားပေးသော အရင်းအမြစ်ပေါင်းစပ်ချက် — သည် ကာဗွန်ခြေရာ၊ လေထုအရည်အသွေး၊ မြို့ပြအပူချိန်ကို ဆုံးဖြတ်သည်။ <strong>ကျောက်မီးသွေး</strong>သည် kWh တစ်ခုလျှင် CO₂ ၈၂၀ ဂရမ် ထုတ်ပြီး <strong>နေရောင်ခြည်</strong>က ၄၁ ဂရမ်သာ ထုတ်သည်။ သို့သော် ပြန်လည်ပြည့်ဖြိုးနိုင်စွမ်းအင်တွင် <strong>မစဲမဆိုင်ရှိမှု</strong> ပြဿနာရှိသည် — နေရောင်ခြည်က နေ့ဘက်သာ၊ လေအားက နာရီအလိုက် ကွဲပြားသည်။ <strong>မြို့ပြအပူကျွန်း</strong>သည် ကွန်ကရစ်နှင့် အပူစွန့်ပစ်မှုကြောင့် ပတ်ဝန်းကျင်ထက် ၂-၈°C ပိုမြင့်သည်။ သစ်ပင်၊ ဥယျာဉ်နှင့် သန့်ရှင်းစွမ်းအင်တို့က မြို့ကို အေးအောင် ကူညီသည်။'
  },
  ai:{
    t:'AI နှင့် LLM များ မည်သို့အလုပ်လုပ်သနည်း',
    d:'AI ၏ ဦးနှောက်အတွင်းသို့ ချုံ့ကြည့်ပါ။ Neural network များ၊ tokenization၊ attention mechanism များနှင့် ChatGPT၊ Claude ကဲ့သို့ မော်ဒယ်များ အမှန်တကယ် စဉ်းစားပုံကို လေ့လာပါ။',
    tag:'နည်းပညာ',
    tab_nn:'Neural Network',
    tab_tokens:'Tokens',
    tab_attention:'Attention',
    tab_scale:'စကေးနှင့် လေ့ကျင့်မှု',
    nn_title:'Neural Network လက်တွေ့ လုပ်ဆောင်ပုံ',
    nn_info:'Neural network များသည် ချိတ်ဆက်ထားသော \'neuron\' အလွှာများ ဖြစ်သည်။ ချိတ်ဆက်မှုတိုင်းတွင် အလေးချိန်ရှိသည်။ အချက်ပြမှုများ input မှ output သို့ စီးဆင်းပြီး အလွှာတိုင်းတွင် data ကို ပြောင်းလဲသည်။ node များကို နှိပ်၍ activation ပြန့်ပွားပုံကို ကြည့်ပါ!',
    nn_fire:'Input အားလုံး ဖွင့်ပါ',
    nn_random:'အလေးချိန် ကျပန်းပြောင်းပါ',
    nn_hint:'အနွေးရောင် = activation မြင့် | အအေးရောင် = activation နိမ့်',
    tokens_title:'အဆင့် ၁ - Tokenization',
    tokens_info:'AI က စာလုံးတွေကို မဖတ်ပါဘူး — သူက <strong>tokens</strong> တွေကိုပဲ ဖတ်တာပါ။ စာသားတွေကို အပိုင်းအစလေးတွေ (tokens) အဖြစ် ခွဲလိုက်ပြီး အဲဒီကမှတစ်ဆင့် သီးခြားနံပါတ် IDs တွေအဖြစ် သတ်မှတ်လိုက်ပါတယ်။',
    tokenize_btn:'Tokenize လုပ်ပါ',
    attention_title:'အဆင့် ၂ - Self-Attention',
    attention_info:'ဒါကတော့ \'လျှို့ဝှက်ချက်\' ပါပဲ။ ၎င်းက token တစ်ခုချင်းစီကို context ရှာဖို့အတွက် အခြား tokens တွေဆီ <strong>ကြည့်ရှု (look at)</strong> ဖို့ ခွင့်ပြုပေးပါတယ်။ ပိုလင်းလေ အာရုံစိုက်မှု (attention) ပိုရလေပါပဲ။',
    scale_title:'အဆင့် ၃ - Parameters နှင့် ဖန်တီးနိုင်စွမ်း',
    scale_info:'ခေတ်သစ် LLMs တွေမှာ ဘီလီယံနဲ့ချီတဲ့ parameters တွေ ရှိပါတယ်။ Temperature က ဖန်တီးနိုင်စွမ်းကို ထိန်းချုပ်ပေးပါတယ် - နိမ့်ရင် ခန့်မှန်းရလွယ်ပြီး မြင့်ရင်တော့ အံ့ဩစရာကောင်းတဲ့ ရလဒ်တွေ ထွက်လာမှာပါ။ Parameter count နဲ့ temperature က AI ရဲ့ လုပ်ဆောင်ပုံအပေါ် ဘယ်လိုသက်ရောက်လဲဆိုတာ ကြည့်ရှုလိုက်ပါ။',
    type_here:'စာသား ဒီမှာရိုက်ပါ...',
    token_count:'Token အရေအတွက်',
    click_word:'၎င်းရဲ့ အာရုံစိုက်မှုကို ကြည့်ဖို့ စာလုံးကို နှိပ်ပါ',
    params:'Parameters',
    temp:'Temperature',
    low:'တည်ငြိမ်မှု',
    high:'ဖန်တီးနိုင်စွမ်း',
    exp_t:'LLM များ တကယ်တမ်း မည်သို့အလုပ်လုပ်သနည်း',
    exp:'<strong>ChatGPT</strong> နှင့် <strong>Claude</strong> ကဲ့သို့သော Large Language Models များကို နောက်စာလုံးကို ခန့်မှန်းနိုင်ရန် စာသားအမြောက်အမြားဖြင့် လေ့ကျင့်ပေးထားပါတယ်။ ၎င်းတို့သည် context ကို နားလည်စေရန် စာလုံးတစ်လုံးချင်းစီကို အခြားစာလုံးများဆီ \'ကြည့်ရှု\' ခွင့်ပြုသည့် self-attention ပါဝင်သော <strong>transformer architecture</strong> ကို အသုံးပြုထားပါတယ်။ လေ့ကျင့်ပေးရာမှာ ခန့်မှန်းမှုအမှားတွေကို လျှော့ချဖို့အတွက် ဘီလီယံနဲ့ချီတဲ့ parameters (weights) တွေကို ချိန်ညှိရပါတယ်။ ရလဒ်ကတော့ ဘာသာစကားပုံစံများ၊ ဆင်ခြင်တုံတရားနှင့် ဗဟုသုတများကို ဖမ်းယူနိုင်တဲ့ model တစ်ခု ထွက်လာတာပါပဲ။ LLMs တွေဟာ လူသားတွေလို \'နားလည်တာ\' မဟုတ်ပါဘူး — ၎င်းတို့ဟာ ဆက်စပ်မှုရှိပြီး အသုံးဝင်တဲ့စာသားတွေကို ထုတ်ပေးနိုင်တဲ့ အလွန်ရှုပ်ထွေးလှတဲ့ ပုံစံတူတိုက်ဆိုင်စစ်ဆေးတဲ့ စက် (pattern-matching machines) များသာ ဖြစ်ပါတယ်။'
  }
}
};
let currentLang='en';
function t(k){const ks=k.split('.');let v=LANG[currentLang];for(const x of ks){if(!v)return k;v=v[x]}return v||k}
function setLang(l){
  currentLang=l;
  document.body.classList.toggle('lang-my',l==='my');
  document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',
    (l==='en'&&b.textContent.trim()==='EN')||(l==='my'&&b.textContent.trim()==='မြန်မာ')));
  document.querySelectorAll('[data-t]').forEach(el=>{el.innerHTML=t(el.dataset.t)});
  handleRoute();
}
